spring:

  datasource:
    # Database connection string.
    url: jdbc:oracle:thin:@localhost:1521/XEPDB1
    driver-class-name: oracle.jdbc.OracleDriver
    username: koratime_user
    password: koratime
    hikari:
      # Max simultaneous DB connections.
      maximum-pool-size: 10
      # Keep 2 ready connections.
      minimum-idle: 2
      connection-timeout: 30000
  jpa:
    # Liquibase manages schema, Hibernate only validates
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml
    enabled: true
    default-schema: KORATIME_USER
  data:
    redis:
      host: localhost
      port: 6379
  mail:
    host: sandbox.smtp.mailtrap.io
    port: 2525
    username: 385557f9ef28e7
    password: 7642b53fe1ed5a
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true

app:
  jwt:
    secret: 7f83b29c0a5e4d3f21b0c9a8f7e6d5c4b3a2910fedcba987654321abcdef0123
    access-token-expiration-ms: 900000      # 15 minutes
    refresh-token-expiration-ms: 604800000  # 7 days
  rate-limit:
    capacity: 20          # max 20 requests
    refill-tokens: 20     # refill to 20
    refill-seconds: 60    # every 60 seconds
    #  cloudinary:
    #    cloud-name: ${CLOUDINARY_NAME:placeholder}
    #    api-key: ${CLOUDINARY_KEY:placeholder}
    #    api-secret: ${CLOUDINARY_SECRET:placeholder}